server:
  port: 8765
spring:
  application:
    name: scheduler-service
  profiles:
    active: dev


mybatis:
    type-aliases-package: com.ydp.etl.scheduler.dao
    mapper-locations: mapper/**Mapper.xml
---
spring:
  profiles: dev
eureka:
  client:
      serviceUrl:
         defaultZone:  http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
datasource:
    jdbc-url: jdbc:mysql://192.168.40.161:3306/etl2
    username: chang
    password: chang
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info

---
spring:
  profiles: prod
eureka:
  client:
      serviceUrl:
         defaultZone:  http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
logging:
  level:
    root: info
  file: log/scheduler.log