spring:
  quartz:
     jdbc:
       initialize-schema: embedded
     job-store-type: jdbc
     properties: #集群配置
        org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreCMT
        org.quartz.scheduler.instanceName: Scheduler
        org.quartz.scheduler.instanceId: AUTO
        org.quartz.threadPool.class:   org.quartz.simpl.SimpleThreadPool
        org.quartz.threadPool.threadCount: 30
        org.quartz.threadPool.threadPriority: 5
        org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
        org.quartz.jobStore.misfireThreshold: 60000
        org.quartz.jobStore.driverDelegateClass:  org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        org.quartz.jobStore.maxMisfiresToHandleAtATime: 10
        org.quartz.jobStore.isClustered: true
        org.quartz.jobStore.clusterCheckinInterval: 20000



